language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t fabiojfl/docker-react -f Dockerfile.dev .

script:
  - docker run fabiojfl/docker-react npm run test -- --coverage