sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t fabiojfl/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true fabiojfl/docker-react npm run test
